"""
Price models — cached commodity prices from external sources
and AI-generated price predictions.
"""

import uuid
from datetime import datetime, date, timezone

from sqlalchemy import String, Date, DateTime, Numeric
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class CommodityPrice(Base):
    """Cached price data from Panel Harga Kementan / Info Pangan Jakarta."""
    __tablename__ = "commodity_prices"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    commodity_name: Mapped[str] = mapped_column(String(100), nullable=False)
    market_name: Mapped[str] = mapped_column(String(255), nullable=False)
    price_per_kg: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    source: Mapped[str] = mapped_column(String(50), nullable=False)  # 'panel_harga_kementan' or 'info_pangan_jakarta'


class PricePrediction(Base):
    """Price predictions generated by the Price Intelligence Agent."""
    __tablename__ = "price_predictions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    commodity_name: Mapped[str] = mapped_column(String(100), nullable=False)
    region: Mapped[str] = mapped_column(String(100), nullable=False)
    predicted_price: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    confidence: Mapped[float] = mapped_column(Numeric(4, 3), nullable=False)
    predicted_for: Mapped[date] = mapped_column(Date, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )
